on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest

      - name: Create build and deploy
        uses: rigdev/actions/build@update
        id: build_rig
        with:
          url: https://rig.infra.rig.dev
          project: matias
          clientID: rig_d3640d9d-70ef-437e-ac7c-f994264cea27
          clientSecret: ${{ secrets.INFRA_CLUSTER_RIG_SECRET }}
          capsule: testcapsule
          image: almostuseful/clockbox:latest
          environment: production
          deploy: true
          # dryRun: true

      # - name: Deploy to capsule
      #   uses: rigdev/actions/deploy@update
      #   id: deploy_rig
      #   with:
      #     url: https://rig.infra.rig.dev
      #     project: matias
      #     clientID: rig_d3640d9d-70ef-437e-ac7c-f994264cea27
      #     clientSecret: ${{ secrets.INFRA_CLUSTER_RIG_SECRET }}
      #     capsule: testcapsule
      #     build: ${{ steps.build_rig.outputs.build }}
      #     environment: production
      #     dryRun: true
          
      - name: Check output
        env:
          OUTPUT: ${{ steps.build_rig.outputs.rolloutConfig }}
        shell: bash
        run: echo $OUTPUT
