on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
      - name: Build Nuntio
        uses: nuntiodev/actions/build@main
        id: build_nuntio
        with:
          email: matias@nuntio.io
          password: ${{ secrets.K8S_NUNTIO_PASSWORD }}
          url: https://k8s-test.nuntio.io
          image: almostuseful/clockbox:latest
          projectID: 801004e6-0c97-4ac9-948c-e31144103986
          msb: "14367851889679157447"
          lsb: "9383905216306800690"
      - name: Deploy to capsule
        uses: nuntiodev/actions/deploy@main
        with:
          email: matias@nuntio.io
          password: ${{ secrets.K8S_NUNTIO_PASSWORD }}
          url: https://k8s-test.nuntio.io
          projectID: 801004e6-0c97-4ac9-948c-e31144103986
          msb: "14367851889679157447"
          lsb: "9383905216306800690"
          buildID: ${{ steps.build_nuntio.outputs.buildID }}
